pipeline {
    agent any
    
    tools {
        dotnetsdk 'dotnet-sdk-8.0'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Restore Dependencies') {
            steps {
                bat 'dotnet restore'
            }
        }
        
        stage('Build') {
    steps {
        bat 'cd InventoryManagement/API'
        bat 'dotnet build InventoryManagement.sln --configuration Release'
    }
}

stage('Test') {
    steps {
        bat 'cd InventoryManagement/API'
        bat 'dotnet test API/InventoryManagement.csproj --configuration Release --no-build'
    }
}

stage('Publish') {
    steps {
        bat 'cd InventoryManagement/API'
        bat 'dotnet publish API/InventoryManagement.csproj --configuration Release --output ./publish'
    }
}

        
        stage('Upload to Artifactory') {
            steps {
                rtUpload (
                    serverId: "artifactory-server",
                    spec: '''{
                        "files": [
                            {
                                "pattern": "publish/",
                                "target": "nuget-local/"
                            }
                        ]
                    }'''
                )
            }
        }
    }
    
    post {
        success {
            echo 'Build completed successfully!'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
