pipeline {
    agent any
    
    tools {
        dotnetsdk 'dotnet-sdk-8.0'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Restore Dependencies') {
            steps {
                bat 'cd InventoryManagement\\API && dotnet restore'
            }
        }
        
        stage('Build') {
            steps {
                bat 'cd InventoryManagement\\API && dotnet build --configuration Release'
            }
        }

        stage('Test') {
            steps {
                bat 'cd InventoryManagement\\API && dotnet test --configuration Release --no-build'
            }
        }

        stage('Publish') {
            steps {
                bat 'cd InventoryManagement\\API && dotnet publish --configuration Release --output .\\publish'
            }
        }
        
        stage('Upload to Artifactory') {
			steps {
				bat 'jf rt upload --url=http://localhost:8082//artifactory --server-id=artifactory-server "InventoryManagement\\API\\publish\\**" nuget-local/'
			}
		}



	}

    
    post {
        success {
            echo 'Build completed successfully!'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
